/**
 * Fork. Store browser-generated media on the server, upstream's way.
 *
 * Upstream's server-side generation writes media bytes into the course's
 * classroom-media directory (`persistClassroomMediaBytes`) and puts the
 * returned `/api/classroom-media/...` reference in the document; its browser
 * generation kept everything in IndexedDB, so a course lost its pictures and
 * sound in any other browser -- a published course's learners included. The
 * owner's browser now uploads through `POST /api/stages/:id/media`, which
 * calls that same function, and records the reference.
 *
 * Best-effort by contract: an upload failure (not the owner, offline, no
 * server persistence) never fails generation. The IndexedDB copy stays exactly
 * as before and is still what this browser plays first.
 */

import { apiPath } from '@/lib/base-path';

function serverPersistenceEnabled(): boolean {
  return typeof window !== 'undefined' && process.env.NEXT_PUBLIC_PERSISTENCE === '1';
}

/** Upload generated bytes; the served reference, or undefined when not stored. */
export async function uploadGeneratedMedia(input: {
  stageId: string;
  blob: Blob;
  mime: string;
  prefix?: string;
  fetchImpl?: typeof globalThis.fetch;
  enabled?: boolean;
}): Promise<string | undefined> {
  const enabled = input.enabled ?? serverPersistenceEnabled();
  if (!enabled || !input.stageId) return undefined;
  const fetchImpl = input.fetchImpl ?? globalThis.fetch;
  try {
    const response = await fetchImpl(
      apiPath(`/api/stages/${encodeURIComponent(input.stageId)}/media`),
      {
        method: 'POST',
        credentials: 'include',
        headers: {
          'content-type': input.mime,
          ...(input.prefix ? { 'x-media-prefix': input.prefix } : {}),
        },
        body: input.blob,
      },
    );
    if (!response.ok) return undefined;
    const body = (await response.json()) as { url?: unknown };
    return typeof body.url === 'string' && body.url ? body.url : undefined;
  } catch {
    return undefined;
  }
}

/** The media type the byte route stores a TTS format under, if it stores it at all. */
export function audioMimeForFormat(format: string): string | undefined {
  const known: Record<string, string> = {
    mp3: 'audio/mpeg',
    mpeg: 'audio/mpeg',
    wav: 'audio/wav',
    ogg: 'audio/ogg',
  };
  return known[format.trim().toLowerCase()];
}
